apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  labels:
      app: nginx
data:
  default.conf: |

        server {
            listen 80;
            charset utf-8;

            location /demo {
                proxy_pass http://demo.demo:8080/;
            }

            location / {
                proxy_pass http://hydra:4444;
            }
        }
