apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-url: https://$host/oauth2/introspect
  name: application
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: demo
          servicePort: 8080
        path: /bar
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
spec:
  rules:
    - http:
        paths:
          - path: /oauth2/introspect
            backend:
              serviceName: auth
              servicePort: 8080
