apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: auth
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
    name: auth
    labels:
      app: auth
spec:
    replicas: 1
    template:
        metadata:
          labels:
            app: auth
        spec:
            containers:
            - name: auth
              image: auth
              env:
              - name: SYSTEM_SECRET
                valueFrom:
                  secretKeyRef:
                    name: auth
                    key: system.secret
              - name: CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: auth
                    key: client.id
              - name: CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: auth
                    key: client.secret
              imagePullPolicy: IfNotPresent
              readinessProbe:
                httpGet:
                  path: /monitor/readiness
                  port: 8080
                initialDelaySeconds: 5
