apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: auth
    tier: backend
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
    name: auth
    labels:
      app: auth
      tier: backend
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: auth
                tier: backend
        spec:
            containers:
            - name: auth
              image: auth
              imagePullPolicy: IfNotPresent
              readinessProbe:
                httpGet:
                  path: /monitor/readiness
                  port: 8080
                initialDelaySeconds: 5
