apiVersion: v1
kind: Service
metadata:
  name: consent
  labels:
    name: consent
spec:
  ports:
    - targetPort: 3000
      port: 3000
  selector:
    app: consent
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: consent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consent
    spec:
      containers:
      - name: consent
        image: oryd/hydra-idp-react:latest
        env:
        - name: HYDRA_URL
          valueFrom:
            configMapKeyRef:
              name: hydra
              key: hydra.url
        - name: HYDRA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: hydra
              key: client.id
        - name: HYDRA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: hydra
              key: client.secret
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        ports:
        - containerPort: 3000

      volumes:
      - name: hydra-volume
        configMap:
          name: hydra
      - name: client-data
        secret:
          secretName: hydra
