apiVersion: v1
kind: Service
metadata:
  name: hydra
  labels:
    name: hydra
spec:
  ports:
    - targetPort: 4444
      port: 4444
  selector:
    app: hydra
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
data:
  hydra.url: https://oauth2.minikube.dev
  consent.url: https://consent.minikube.dev
  .hydra.yml: |
    cluster_url: https://localhost:4444
    client_id: admin
    client_secret: demo-password
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: hydra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
      - name: hydra
        image: oryam/hydra:latest
        env:
        - name: SYSTEM_SECRET
          valueFrom:
            secretKeyRef:
              name: hydra
              key: system.secret
        - name: CONSENT_URL
          valueFrom:
            configMapKeyRef:
              name: hydra
              key: consent.url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hydra
              key: database.url
        - name: FORCE_ROOT_CLIENT_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: hydra
              key: client
        args:
        - host
        - --dangerous-auto-logon
        - --disable-telemetry
        ports:
        - name: default
          containerPort: 4444
        - name: other
          containerPort: 4445
        volumeMounts:
        - name: hydra-volume
          mountPath: /root
      volumes:
      - name: hydra-volume
        configMap:
          name: hydra
