apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-migrate
spec:
  template:
    metadata:
      name: hydra-migrate
    spec:
      containers:
      - command:
        - hydra
        - migrate
        - sql
        - postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
        image: oryd/hydra:latest
        name: hydra-migrate
      restartPolicy: Never
