apiVersion: v1
kind: Service
metadata:
  name: hydra
  labels:
    name: hydra
spec:
  ports:
    - targetPort: 4444
      port: 4444
  selector:
    app: hydra
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
data:
  hydra.url: https://192.168.34.194/hydra
  consent.url: https://192.168.34.194/
  .hydra.yml: |
    cluster_url: https://192.168.34.194/hydra
    client_id: admin
    client_secret: demo-password
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: hydra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
      - name: hydra
        image: oryd/hydra:latest
        env:
        - name: SYSTEM_SECRET
          valueFrom:
            secretKeyRef:
              name: hydra
              key: system.secret
        - name: ISSUER
          value: https://192.168.34.194/hydra
        - name: CONSENT_URL
          valueFrom:
            configMapKeyRef:
              name: hydra
              key: consent.url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hydra
              key: database.url
        - name: FORCE_ROOT_CLIENT_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: hydra
              key: client
        - name: LOG_LEVEL
          value: debug
        - name: HTTPS_ALLOW_TERMINATION_FROM
          value: 0.0.0.0/0
        command:
        - hydra
        - host
        - --dangerous-auto-logon
        - --disable-telemetry
        ports:
        - name: default
          containerPort: 4444
        - name: other
          containerPort: 4445
        volumeMounts:
        - name: hydra-volume
          mountPath: /root
      volumes:
      - name: hydra-volume
        configMap:
          name: hydra
