{{- $serviceName := include "fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
      ingress.kubernetes.io/server-snippet: |

            location /_dummy {
                internal;
                set $scopes "";
            }

            location = /external-auth {

                internal;
                set $proxy_upstream_name "external-authentication";

                proxy_pass_request_body     off;
                proxy_set_header            Content-Length "";

                proxy_set_header            Scopes                  $scopes;
                proxy_set_header            Host                    $host;
                proxy_set_header            X-Original-URL          $scheme://$http_host$request_uri;
                proxy_set_header            X-Auth-Request-Redirect $request_uri;
                proxy_set_header            X-Sent-From             "nginx-ingress-controller";

                proxy_ssl_server_name       on;
                proxy_pass_request_headers  on;
                client_max_body_size        "1m";

                set $target https://$host/oauth2/introspect;
                proxy_pass $target;
            }
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.config.ports.service }}
        path: /oauth2
  {{- if .Values.config.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
