apiVersion: v1
kind: Service
metadata:
 name: {{ template "fullname" . }}
 labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.config.ports.service }}
    targetPort: {{ .Values.config.ports.deployment }}
    protocol: TCP
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
