from random import randrange

def random_campground():
    if 'campgrounds' not in random_campground.__dict__:
        random_campground.campgrounds = campgrounds()
    i = randrange(0,len(random_campground.campgrounds))
    return random_campground.campgrounds[i]

def campgrounds():
    return [{"parkId":"banff", "campgroundId":"johnston_canyon", "sectionId":"1-63"},
        {"parkId":"banff", "campgroundId":"johnston_canyon", "sectionId":"64-132"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-trailer_court", "sectionId":"a"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-trailer_court", "sectionId":"b"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-trailer_court", "sectionId":"c"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"a"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"b"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"c"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"d"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"e"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"f"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"g"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"h"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"i"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"j"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_1", "sectionId":"k"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_2", "sectionId":"a"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_2", "sectionId":"b"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_2", "sectionId":"c"},
        {"parkId":"banff", "campgroundId":"tunnel_mountain-village_2", "sectionId":"d"},
        {"parkId":"banff", "campgroundId":"two_jack_lakeside", "sectionId":"1-13"},
        {"parkId":"banff", "campgroundId":"two_jack_lakeside", "sectionId":"14-35"},
        {"parkId":"banff", "campgroundId":"two_jack_lakeside", "sectionId":"36-74"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"1-4,7-10"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"5-6,11-13"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"14-17"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"18-21"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"22-27"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"28-30"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"31-34"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"35-38"},
        {"parkId":"banff", "campgroundId":"two_jack_main", "sectionId":"39-44"},
        {"parkId":"banff_backcountry", "campgroundId":"aylmer_pass_junction"},
        {"parkId":"banff_backcountry", "campgroundId":"aylmer_canyon"},
        {"parkId":"banff_backcountry", "campgroundId":"badger_pass"},
        {"parkId":"banff_backcountry", "campgroundId":"baker_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"ball_pass_junction"},
        {"parkId":"banff_backcountry", "campgroundId":"big_springs"},
        {"parkId":"banff_backcountry", "campgroundId":"bighorn_backcountry"},
        {"parkId":"banff_backcountry", "campgroundId":"birdwood"},
        {"parkId":"banff_backcountry", "campgroundId":"block_lacks"},
        {"parkId":"banff_backcountry", "campgroundId":"bow_river"},
        {"parkId":"banff_backcountry", "campgroundId":"bow_valley"},
        {"parkId":"banff_backcountry", "campgroundId":"brewster_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"bryant_creek_shelter"},
        {"parkId":"banff_backcountry", "campgroundId":"burstall"},
        {"parkId":"banff_backcountry", "campgroundId":"cascade_bridge"},
        {"parkId":"banff_backcountry", "campgroundId":"casteguard"},
        {"parkId":"banff_backcountry", "campgroundId":"don_getty_wildland"},
        {"parkId":"banff_backcountry", "campgroundId":"egypt_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"egypt_lake_shelter"},
        {"parkId":"banff_backcountry", "campgroundId":"don_getty_wildland"},
        {"parkId":"banff_backcountry", "campgroundId":"elk_summit"},
        {"parkId":"banff_backcountry", "campgroundId":"fish_lakes"},
        {"parkId":"banff_backcountry", "campgroundId":"flints_park"},
        {"parkId":"banff_backcountry", "campgroundId":"floe_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"ghost_lakes"},
        {"parkId":"banff_backcountry", "campgroundId":"ghost_river"},
        {"parkId":"banff_backcountry", "campgroundId":"glacier_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"healy_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"hector_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"height_of_the_rockies"},
        {"parkId":"banff_backcountry", "campgroundId":"helmet_falls"},
        {"parkId":"banff_backcountry", "campgroundId":"helmet/ochre_junction"},
        {"parkId":"banff_backcountry", "campgroundId":"hidden_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"howard_douglas_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"johnston_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"larrys_camp"},
        {"parkId":"banff_backcountry", "campgroundId":"laughing_falls"},
        {"parkId":"banff_backcountry", "campgroundId":"little_yoho"},
        {"parkId":"banff_backcountry", "campgroundId":"lost_horse_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"luellen_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"marvel_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"mcarthur_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"mcbrides_camp"},
        {"parkId":"banff_backcountry", "campgroundId":"merlin_meadows"},
        {"parkId":"banff_backcountry", "campgroundId":"molar_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"mosquito_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"mount_rundle"},
        {"parkId":"banff_backcountry", "campgroundId":"mount_cockscomb"},
        {"parkId":"banff_backcountry", "campgroundId":"mount_inglismaldie"},
        {"parkId":"banff_backcountry", "campgroundId":"mount_costigan"},
        {"parkId":"banff_backcountry", "campgroundId":"mount_assiniboine"},
        {"parkId":"banff_backcountry", "campgroundId":"mystic_junction"},
        {"parkId":"banff_backcountry", "campgroundId":"mystic_valley"},
        {"parkId":"banff_backcountry", "campgroundId":"norman_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"numa_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"paradise_valley"},
        {"parkId":"banff_backcountry", "campgroundId":"peter_lougheed"},
        {"parkId":"banff_backcountry", "campgroundId":"pharaoh_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"red_deer_lakes"},
        {"parkId":"banff_backcountry", "campgroundId":"sawback_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"shadow_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"siffleur_wilderness_area"},
        {"parkId":"banff_backcountry", "campgroundId":"siffleur_river"},
        {"parkId":"banff_backcountry", "campgroundId":"spray_valley"},
        {"parkId":"banff_backcountry", "campgroundId":"stoney_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"taylor_lake"},
        {"parkId":"banff_backcountry", "campgroundId":"the_narrows"},
        {"parkId":"banff_backcountry", "campgroundId":"tumbling_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"twin_lakes"},
        {"parkId":"banff_backcountry", "campgroundId":"twin_falls"},
        {"parkId":"banff_backcountry", "campgroundId":"verdant_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"white_goat_wilderness"},
        {"parkId":"banff_backcountry", "campgroundId":"wildflower_creek"},
        {"parkId":"banff_backcountry", "campgroundId":"yoho_lake"},
        {"parkId":"banff_lake_louise", "campgroundId":"soft_sided", "sectionId":"a,b,c"},
        {"parkId":"banff_lake_louise", "campgroundId":"soft_sided", "sectionId":"d,e"},
        {"parkId":"banff_lake_louise", "campgroundId":"soft_sided", "sectionId":"g,h,i"},
        {"parkId":"banff_lake_louise", "campgroundId":"soft_sided", "sectionId":"j,k"},
        {"parkId":"banff_lake_louise", "campgroundId":"soft_sided", "sectionId":"l,m"},
        {"parkId":"banff_lake_louise", "campgroundId":"hard_sided", "sectionId":"1-34,72-97"},
        {"parkId":"banff_lake_louise", "campgroundId":"hard_sided", "sectionId":"b47-71,114-135"},
        {"parkId":"banff_lake_louise", "campgroundId":"hard_sided", "sectionId":"b34a-46,98-113"},
        {"parkId":"banff_lake_louise", "campgroundId":"hard_sided", "sectionId":"136-163,164-189"},
        {"parkId":"bruce_peninsula", "campgroundId":"cyprus_lake", "sectionId":"poplars"},
        {"parkId":"bruce_peninsula", "campgroundId":"cyprus_lake", "sectionId":"birches"},
        {"parkId":"bruce_peninsula", "campgroundId":"cyprus_lake", "sectionId":"tamarack"},
        {"parkId":"bruce_peninsula", "campgroundId":"cyprus_lake", "sectionId":"yurts"},
        {"parkId":"bruce_peninsula", "campgroundId":"backcountry_campsites"},
        {"parkId":"cape_breton_highlands", "campgroundId":"broad_cove", "sectionId":"1-34"},
        {"parkId":"cape_breton_highlands", "campgroundId":"broad_cove", "sectionId":"35-83"},
        {"parkId":"cape_breton_highlands", "campgroundId":"broad_cove", "sectionId":"84-141"},
        {"parkId":"cape_breton_highlands", "campgroundId":"broad_cove", "sectionId":"142-202"},
        {"parkId":"cape_breton_highlands", "campgroundId":"cheticamp"},
        {"parkId":"cape_breton_highlands", "campgroundId":"ingonish_beach", "sectionId":"1-34,37-60"},
        {"parkId":"cape_breton_highlands", "campgroundId":"ingonish_beach", "sectionId":"o35-o36"},
        {"parkId":"elk_island", "campgroundId":"astotin_lake_campground", "sectionId":"1-40,o9-o11,o20"},
        {"parkId":"elk_island", "campgroundId":"astotin_lake_campground", "sectionId":"42-80,o34,o41"},
        {"parkId":"elk_island", "campgroundId":"backcountry_campsites"},
        {"parkId":"forillon", "campgroundId":"cap-bon-ami_overview"},
        {"parkId":"forillon", "campgroundId":"petit-gaspe_overview"},
        {"parkId":"forillon", "campgroundId":"des-rosiers_overview"},
        {"parkId":"fort_langley", "campgroundId":"otentiks_o1-o5"},
        {"parkId":"fort_rodd_hill", "campgroundId":"otentiks_o1-o5"},
        {"parkId":"fundy", "campgroundId":"chignecto_north", "sectionId":"1-79"},
        {"parkId":"fundy", "campgroundId":"chignecto_north", "sectionId":"80-161"},
        {"parkId":"fundy", "campgroundId":"chignecto_north", "sectionId":"165-290"},
        {"parkId":"fundy", "campgroundId":"headquarters", "sectionId":"1-30"},
        {"parkId":"fundy", "campgroundId":"headquarters", "sectionId":"34-58"},
        {"parkId":"fundy", "campgroundId":"headquarters", "sectionId":"59-124"},
        {"parkId":"fundy", "campgroundId":"headquarters", "sectionId":"yurts"},
        {"parkId":"fundy", "campgroundId":"point_wolfe", "sectionId":"1-20,154-169,otentiks_o4-o16"},
        {"parkId":"fundy", "campgroundId":"point_wolfe", "sectionId":"g21-62,134-147,152,153"},
        {"parkId":"fundy", "campgroundId":"point_wolfe", "sectionId":"63-133"},
        {"parkId":"fundy", "campgroundId":"fundy_backcountry"},
        {"parkId":"fundy", "campgroundId":"wolfe_lake"},
        {"parkId":"fundy", "campgroundId":"cannontown"},
        {"parkId":"georgian_bay_islands", "campgroundId":"cedar_spring_and_christian_beach", "sectionId":"1,3-24,o1"},
        {"parkId":"georgian_bay_islands", "campgroundId":"cedar_spring_and_christian_beach", "sectionId":"2,25-45,o2-o5"},
        {"parkId":"georgian_bay_islands", "campgroundId":"cedar_spring_and_christian_beach", "sectionId":"cedar_spring_cabins_1-6"},
        {"parkId":"georgian_bay_islands", "campgroundId":"cedar_spring_and_christian_beach", "sectionId":"christian_beach_cabins_1-4"},
        {"parkId":"georgian_bay_islands", "campgroundId":"backcountry_campsites"},
        {"parkId":"grasslands", "campgroundId":"frenchman_valley"},
        {"parkId":"grasslands", "campgroundId":"rock_creek"},
        {"parkId":"grasslands", "campgroundId":"two_trees"},
        {"parkId":"grasslands", "campgroundId":"backcountry_campsites"},
        {"parkId":"gros_morne", "campgroundId":"berry_hill_and_green_point", "sectionId":"berry_hill_and_green_point_campgrounds"},
        {"parkId":"gros_morne", "campgroundId":"berry_hill_and_green_point", "sectionId":"rustic_cabins"},
        {"parkId":"gros_morne", "campgroundId":"shallow_bay"},
        {"parkId":"gros_morne", "campgroundId":"trout_river_pond"},
        {"parkId":"gulf_islands", "campgroundId":"mcdonald"},
        {"parkId":"gulf_islands", "campgroundId":"sidney_spit"},
        {"parkId":"gulf_islands", "campgroundId":"prior_centennial"},
        {"parkId":"gulf_islands", "campgroundId":"backcountry_campsites"},
        {"parkId":"jasper", "campgroundId":"pocahontas", "sectionId":"b"},
        {"parkId":"jasper", "campgroundId":"pocahontas", "sectionId":"c"},
        {"parkId":"jasper", "campgroundId":"pocahontas", "sectionId":"d"},
        {"parkId":"jasper", "campgroundId":"pocahontas", "sectionId":"e"},
        {"parkId":"jasper", "campgroundId":"pocahontas", "sectionId":"f"},
        {"parkId":"jasper", "campgroundId":"wabasso", "sectionId":"a"},
        {"parkId":"jasper", "campgroundId":"wabasso", "sectionId":"b"},
        {"parkId":"jasper", "campgroundId":"wabasso", "sectionId":"c"},
        {"parkId":"jasper", "campgroundId":"wabasso", "sectionId":"d"},
        {"parkId":"jasper", "campgroundId":"wapiti", "sectionId":"a-d"},
        {"parkId":"jasper", "campgroundId":"wapiti", "sectionId":"e,f,ff,g,h"},
        {"parkId":"jasper", "campgroundId":"wapiti", "sectionId":"i,j,k,l"},
        {"parkId":"jasper", "campgroundId":"wapiti", "sectionId":"m,n,o,p"},
        {"parkId":"jasper", "campgroundId":"wapiti", "sectionId":"q,r,rr"},
        {"parkId":"jasper", "campgroundId":"wapiti", "sectionId":"s,t,u,v"},
        {"parkId":"jasper", "campgroundId":"wapiti", "sectionId":"w,x,y"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"0-5"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"6-10"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"11-14"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"15-19"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"20-25"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"26-28"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"29-30"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"50-52"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"53-56"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"75-59"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"60-61"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"62-64"},
        {"parkId":"jasper", "campgroundId":"whistlers", "sectionId":"65-67"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"athabasca_pass_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"athabasca_river"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"brazeau_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"fiddle_river"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"fortress_lake_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"fryatt_valley_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"geraldine_lakes_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"jacques_lake_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"maligne_lake"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"maligne_pass_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"north_boundary_and_celestine_lake_trails"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"saturday_night_lake_loop_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"skyline_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"south_boundary_trail"},
        {"parkId":"jasper", "campgroundId":"backcountry_campsites", "sectionId":"tonquin_valley_trail"},
        {"parkId":"jasper", "campgroundId":"palisades"}]
