apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: demo
    namespace: demo
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - name: api
                  image: allankerr/api
                  ports:
                      - containerPort: 8080
