apiVersion: v1
kind: Service
metadata:
    name: demo
    labels:
        app: api
spec:
    selector:
        app: api
    ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
