# /***************************************************************************************
# *    Title: Example: Deploying Cassandra with Stateful Sets
# *    Author: Kubernetes
# *    Date: Sep. 15, 2017
# *    Code version: 1.0
# *    Availability: https://kubernetes.io/docs/tutorials/stateful-application/cassandra/
# *
# ***************************************************************************************/
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra
